version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/chat-app

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 60
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 60
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
